language: elixir

elixir:
  - 1.2.6
  - 1.3.2

otp_release:
  - 18.3
  - 19.0

script:
  - MIX_ENV=test mix compile
  - MIX_ENV=test mix test --cover
  
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
