language: elixir

elixir:
  - 1.4.5
  - 1.5.1

otp_release:
  - 19.3
  - 20.0

script:
  - MIX_ENV=test mix coveralls.travis --force
  
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
