language: elixir

elixir:
  - 1.7.4
  - 1.8.1

otp_release:
  - 20.3.8
  - 21.2.6

script:
  - MIX_ENV=test mix coveralls.travis --force
  
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
